name: Slack Integration Workflow

on:
  push:
    branches:
      - master

jobs:
  generate-debug:
    runs-on: ubuntu-latest
    
    steps:

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
       
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make gradlew Executable
        run: chmod +x $GITHUB_WORKSPACE/gradlew

      - name: Build with Gradle Wrapper
        run: |
          # cd $GITHUB_WORKSPACE
          # ./gradlew assembleDebug

      # - name: Find and store APK file paths
      #   run: |
      #     apkfiles=$(find app/build/outputs/apk/debug/app-debug.apk -exec echo "{}" \;)
      #     apkfile_list=""
      #     for apk in $apkfiles; do
      #       apkfile_list="$apkfile_list$apk,"
      #     done
      #     echo "APK_FILES=$apkfile_list" >> $GITHUB_ENV
          
      # - name: Post to Slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     channel-id: D05PH59CMU2
      #     slack-message: "Hey this is testing message"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Print Repository Directory Structure
        run: ls -R
      
      - name: Post to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          channel: android-builds
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path:  app/build/outputs/apk/debug/app-debug.apk 
          initial_comment: "This is debug APK"
