name: Slack Integration Workflow

on:
  push:
    branches:
      - master

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: D05PH59CMU2
          slack-message: "Hey this is testing message"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
