name: Slack Integration Workflow

on:
  push:
    branches:
      - master

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Post to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: android-builds
          initial_comment: "Hey this is testing message"
